### PR TITLE
Switch to reStructuredText for Readme

### LINKED ISSUE #99: Switch to reStructuredText for Readme
In [sentinel5dl](https://github.com/emissions-api/sentinel5dl) and  [sentinel5algorithms](https://github.com/emissions-api/sentinel5algorithms) we used [reStructuredText](https://de.wikipedia.org/wiki/ReStructuredText) for the Readme to easily be able to add it to the documentation. I would suggest doing the same for this repository.

### PR DESCRIPTION
**Pull request by shaardie**
We are using reStructuredText for the documentation as well as in our other
repositories. This patch does not change the content of the Readme, but
converts it to reStructuredText to streamline it with the rest of our work.

Closes #99

### CODE REVIEW

**Comment by shaardie** [comment]
I we agree on #99, we can use this Pull Request to switch to reStructuredText.

**Comment by lkiesow** [comment]
If no one speaks up against this until tomorrow, I will merge this.

**Comment by shaardie** [comment]
@lkiesow Do you merge this?

**Comment by lkiesow** [comment]
Sorry, forgot about this → merged

**Pull request merged**
