### PR TITLE
add doc generation + deployment to .travis.yml

### LINKED ISSUE #53: Automatically build the docs
We can automatically build our documentation with sphinx. We should do exactly that using our CI and host the code with github-pages.

### PR DESCRIPTION
**Pull request by brennerm**
Fixes #53

### CODE REVIEW

**Comment by brennerm** [comment]
Please generate and add a personal access token according to this docu.
https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token

**Comment by brennerm** [comment]
Also make sure that the Pages feature is enabled for this repo and points to the gh-pages branch. If you need further support feel free to message me.

**Comment by lkiesow** [comment]
Available at: https://emissions-api.org/emissions-api/
@tibroc, do we want to move this to docs.emissions-api.org?

**Comment by tibroc** [comment]
@lkiesow that would make sense, yes.

**Pull request merged**
