### PR TITLE
Drop 'id' from carbonmonoxide table

### PR DESCRIPTION
**Pull request by shaardie**
We do have an `id` on the carbonmonoxide table which we are not using.
So we should drop it to save space.

### CODE REVIEW

**Comment by shaardie** [comment]
I tested this for only a month and these are the results:

```
# Time to migrate
alembic upgrade head  0.65s user 0.79s system 0% cpu 2:28.43 total
```

As raw SQL Commands alembic would run the following commands
```sql
$ alembic upgrade --sql f781a3528157:22ea33634af6
BEGIN;

INFO  [alembic.runtime.migration] Running upgrade f781a3528157 -> 22ea33634af6, Drop primary key of carbonmonoxide
-- Running upgrade f781a3528157 -> 22ea33634af6

ALTER TABLE carbonmonoxide DROP COLUMN id;

ALTER TABLE carbonmonoxide ADD CONSTRAINT carbonmonoxide_pkey PRIMARY KEY (timestamp, geom);

UPDATE alembic_version SET version_num='22ea33634af6' WHERE alembic_version.version_num = 'f781a3528157';

COMMIT;
```

And for the downgrade

```sql
$ alembic downgrade --sql 22ea33634af6:f781a3528157
BEGIN;

INFO  [alembic.runtime.migration] Running downgrade 22ea33634af6 -> f781a3528157, Drop primary key of carbonmonoxide
-- Running downgrade 22ea33634af6 -> f781a3528157

CREATE SEQUENCE carbonmonoxide_id_seq;

ALTER TABLE carbonmonoxide ADD COLUMN id INTEGER DEFAULT nextval('carbonmonoxide_id_seq'::regclass) NOT NULL;

ALTER TABLE carbonmonoxide DROP CONSTRAINT carbonmonoxide_pkey;

ALTER TABLE carbonmonoxide ADD CONSTRAINT carbonmonoxide_pkey PRIMARY KEY (id);

UPDATE alembic_version SET version_num='f781a3528157' WHERE alembic_version.version_num = '22ea33634af6';

COMMIT;
```

The downgrade step is actually not the same than before, since the sequence `carbonmonoxide_id_seq` is not owned by the `carbonmonoxide` table, but these are the step recommended by alembic.

But actually this in this configuration this migration totally fails its purpose, since the size of the table actually increase :laughing:

```sql 
--- Before ---
        relation        | total_size 
------------------------+------------
 public.carbonmonoxide  | 16 GB
 public.spatial_ref_sys | 7184 kB
 public.us_rules        | 456 kB
 tiger.pagc_rules       | 456 kB
 public.us_lex          | 312 kB

--- After ---
        relation        | total_size 
------------------------+------------
 public.carbonmonoxide  | 20 GB
 public.spatial_ref_sys | 7184 kB
 public.us_rules        | 456 kB
 tiger.pagc_rules       | 456 kB
 public.us_lex          | 312 kB
```

My guess is the extra index on the tuple `(timestamp, geom)`.

**Comment by shaardie** [comment]
I updated the pull request so I updated https://github.com/emissions-api/emissions-api/pull/168#issuecomment-568488643 respectively

**Comment by EmbeddedHenni** [comment]
i think the first answer in [this](https://stackoverflow.com/questions/14588304/composite-primary-key-vs-additional-id-column) post got an additional point about _why ID isnt a replacement for composite index_

**Comment by shaardie** [comment]
> i think the first answer in [this](https://stackoverflow.com/questions/14588304/composite-primary-key-vs-additional-id-column) post got an additional point about _why ID isnt a replacement for composite index_

I am not quite sure what you mean. We do not try to replace composite index with an id. We remove the id as a primary key completely and replace it with a composite primary key.

**Comment by lkiesow** [comment]
Reading the first answer I'm also not sure why it couldn't be a replacement?

**Comment by lkiesow** [comment]
If we want to drop `id`, it really only makes sense to drop the CO ORM object like this:

```diff
diff --git a/emissionsapi/db.py b/emissionsapi/db.py
index 5bf61cf..95b2280 100644
--- a/emissionsapi/db.py
+++ b/emissionsapi/db.py
@@ -10,7 +10,7 @@ import logging
 
 import sqlalchemy
 from sqlalchemy import and_, or_, create_engine, Column, DateTime, Integer, \
-        Float, String, PickleType
+        Float, String, PickleType, Table, MetaData
 from sqlalchemy.ext.declarative import declarative_base
 from sqlalchemy.orm import sessionmaker
 
@@ -28,6 +28,8 @@ logger = logging.getLogger(__name__)
 # Retrieved as environment variable.
 database = config('database') or 'postgresql://user:user@localhost/db'
 
+metadata = MetaData()
+
 # Global session variable. Set on initialization.
 __session__ = None
 
@@ -96,6 +98,14 @@ class Cache(Base):
         session.commit()
 
 
+carbonmonoxide = Table('carbonmonoxide', metadata,
+    Column('value', Float),
+    Column('timestamp', DateTime, index=True),
+    Column('geom', geoalchemy2.Geometry(geometry_type='POINT'))
+)
+
+
+'''
 class Carbonmonoxide(Base):
     """ORM object for carbon monoxide point
     """
@@ -114,6 +124,7 @@ class Carbonmonoxide(Base):
         self.timestamp = timestamp
         self.geom = geoalchemy2.elements.WKTElement(
             f"POINT({longitude} {latitude})")
+'''
 
 
 def with_session(f):
@@ -157,12 +168,13 @@ def get_session():
             database, echo=logger.getEffectiveLevel() == logging.DEBUG)
         __session__ = sessionmaker(bind=Engine)
         Base.metadata.create_all(Engine)
+        carbonmonoxide.create(Engine)
 
     # Return new session object
     return __session__()
 
 
-def insert_dataset(session, data, tbl=Carbonmonoxide):
+def insert_dataset(session, data, tbl=carbonmonoxide):
     '''Batch insert data into the database using PostGIS specific functions.
 
     :param session: SQLAlchemy Session
@@ -172,7 +184,7 @@ def insert_dataset(session, data, tbl=Carbonmonoxide):
     :param tbl: Base class representing the database table for the data
     :type tbl: sqlalchemy.ext.declarative.api.DeclarativeMeta
     '''
-    columns = [tbl.value, tbl.timestamp, tbl.geom]
+    columns = [tbl.c.value, tbl.c.timestamp, tbl.c.geom]
     values = sqlalchemy.select([sqlalchemy.func.unnest(data.value),
                                 sqlalchemy.func.unnest(data.timestamp),
                                 sqlalchemy.func.ST_MakePoint(
```

The resulting table has no primary key but all the data we need:

```sql
emissionsapi=> select * from carbonmonoxide limit 5;
        value        |        timestamp        |                    geom                    
---------------------+-------------------------+--------------------------------------------
 0.00838769972324371 | 2019-01-01 01:23:31.235 | 0101000000000000A061FA354000000060BFE052C0
 0.00793243851512671 | 2019-01-01 01:23:32.315 | 01010000000000008097FC3540000000E0B0E452C0
 0.00793604459613562 | 2019-01-01 01:23:34.475 | 010100000000000080390136400000002094EC52C0
  0.0072003030218184 | 2019-01-01 01:23:35.555 | 01010000000000008091033640000000A085F052C0
 0.00867919251322746 | 2019-01-01 01:23:37.715 | 0101000000000000405F0836400000002068F852C0
(5 rows)
```

**Comment by lkiesow** [comment]
Had to strugle a bit with alembic but that's a separate issue → merged

**Pull request merged**
